import { StyleSheet } from 'react-native';
import COLORS from '../../utils/Colors';
import { horizontalScale, verticalScale } from '../../utils/Metrics';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: verticalScale(16),
    paddingVertical: verticalScale(12),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderbottom,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.headertitle,
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.text2,
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(8),
    borderRadius: 8,
    gap: 6,
  },
  downloadButtonText: {
    color: COLORS.white,
    fontWeight: '600',
    fontSize: 14,
  },
  invoiceCard: {
    backgroundColor: COLORS.white,
    margin: 16,
    borderRadius: 12,
    padding: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  invoiceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  invoiceLabel: {
    fontSize: 12,
    color: COLORS.headertext,
    fontWeight: '500',
    marginBottom: 2,
  },
  invoiceNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.headertitle,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: verticalScale(6),
    borderRadius: 20,
  },
  statusText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.inputBackground,
    marginVertical: verticalScale(12),
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(12),
  },
  infoColumn: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: COLORS.headertext,
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 14,
    color: COLORS.headertitle,
    fontWeight: '500',
  },
  addressSection: {
    marginTop: verticalScale(12),
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.headertitle,
    marginBottom: verticalScale(12),
  },
  addressCard: {
    backgroundColor: COLORS.halfmodal,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.bordercolor
  },
  addressText: {
    fontSize: 14,
    color: COLORS.reviewcmt,
    marginBottom: 4,
  },
  itemsCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginBottom: verticalScale(16),
    borderRadius: 12,
    padding: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  itemsHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderbottom,
    paddingBottom: verticalScale(8),
    marginBottom: verticalScale(8),
  },
  itemHeaderTextProducts: {
    flex: 2,
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.headertext,
    textTransform: 'uppercase',
  },
  itemHeaderText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.headertext,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  itemRow: {
    flexDirection: 'row',
    paddingVertical: verticalScale(8),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderbottom,
    alignItems: 'center',
  },
  productInfoContainer: {
    flex: 2,
  },
  productName: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.headertitle,
    marginBottom: 2,
  },
  productDetails: {
    fontSize: 12,
    color: COLORS.headertext,
  },
  itemTextQuantity: {
    flex: 1,
    fontSize: 14,
    color: COLORS.review,
    textAlign: 'center',
  },
  itemTextPrice: {
    flex: 1,
    fontSize: 14,
    color: COLORS.review,
    textAlign: 'center',
  },
  itemTextTotal: {
    flex: 1,
    fontSize: 14,
    color: COLORS.review,
    textAlign: 'center',
  },
  summaryCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginBottom: verticalScale(16),
    borderRadius: 12,
    padding: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalScale(8),
  },
  summaryLabel: {
    fontSize: 14,
    color: COLORS.headertext,
  },
  summaryValue: {
    fontSize: 14,
    color: COLORS.review,
    fontWeight: '500',
  },
  summaryValueDiscount: {
    fontSize: 14,
    color: '#10B981',
    fontWeight: '500',
  },
  totalDivider: {
    height: 1,
    backgroundColor: COLORS. borderbottom,
    marginVertical: verticalScale(12),
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.headertitle,
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#3B82F6',
  },
  notesCard: {
    backgroundColor: '#F0F9FF',
    marginHorizontal: 16,
    marginBottom: verticalScale(16),
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0F2FE',
  },
  notesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0369A1',
    marginTop: verticalScale(8),
    marginBottom: verticalScale(8),
  },
  notesText: {
    fontSize: 14,
    color: '#0C4A6E',
    textAlign: 'center',
    lineHeight: 20,
  },
  boldText: {
    fontWeight: 'bold',
  },
  supportCard: {
    backgroundColor: '#FEF3C7',
    marginHorizontal: 16,
    marginBottom: verticalScale(32),
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  supportText: {
    fontSize: 12,
    color: '#92400E',
    textAlign: 'center',
    fontStyle: 'italic',
  },
});
