export const base_url = 'https://revista-sa.com';
const Api_url = `${base_url}/api/v4/`;

export const Base_Url = {
  login: `${Api_url}auth/login`,
  signup: `${Api_url}auth/register`,
  banner: `${Api_url}banners`,
  categories: `${Api_url}categories/popular-categories`,
  allcategory:`${Api_url}categories`,
  handmadecategory:`${Api_url}handmade-categories`,
  latestpro:`${Api_url}products/latest`,
  addtocart:`${Api_url}cart/add`,
  getcart:`${Api_url}cart`,
  updatecart:`${Api_url}cart/update`,
  cartremove:`${Api_url}cart/remove`,
  clearCart:`${Api_url}cart/remove-all`,
  addReview:`${Api_url}products/reviews/submit`,
  getAddress:`${Api_url}customer/address/getlist`,
  addWishlist:`${Api_url}customer/wish-list/add`,
  wishlistremove:`${Api_url}customer/wish-list/remove`,
  getWishlist:`${Api_url}customer/wish-list`,
  clearWishlist:`${Api_url}customer/wish-list/clear-all`,
  getProfile:`${Api_url}customer/info`,
  updateProfile:`${Api_url}customer/update-profile`,
  flashsale:`${Api_url}flash-deals`,
  search:`${Api_url}products/search`,  
  logout:`${Api_url}auth/logout`,
  magzinecategory:`${Api_url}magazine/categories`,
  magzineproduct:`${Api_url}magazine/products`,
  topseller:`${Api_url}seller/top`,
  allseller:`${Api_url}seller/all`,
  getProductsBySeller:`${Api_url}products/getProductsBySeller`,
  placeorder:`${Api_url}customer/order/placeOrder`,
  getorder:`${Api_url}customer/order/list`,
  handmade:`${Api_url}products/homemadeProducts`,
  brandedproduct:`${Api_url}brands/products`,
  address:`${Api_url}customer/address/add1`, 
  subscriptionplan:`${Api_url}customer/plans`,
  purchasesubscriptionplans:`${Api_url}customer/plan-subscription`,
  handmadeurl:`${Api_url}handmade-categories`,
  primemember:`${Api_url}products/membershipIcon`,
  submitreview:`${Api_url}products/review/submit`,
  relatedproduct:`${Api_url}products/related-products`,
};
