import { StyleSheet } from 'react-native';
import COLORS from '../../utils/Colors';

const styles = StyleSheet.create({
  container: { padding: 16, backgroundColor: COLORS.white, flexGrow: 1 },
  summaryBox: {
    backgroundColor: '#f8faff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 6 },
  label: { fontSize: 16, color: COLORS.reviewcmt },
  value: { fontSize: 16, color: COLORS.redblack },
  totalLabel: { fontWeight: 'bold', fontSize: 18 },
  totalValue: { fontWeight: 'bold', fontSize: 18, color: '#03a709ff' },
  couponRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  couponInput: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 10,
    fontSize: 15,
  },
  couponBtn: {
    marginLeft: 8,
    backgroundColor: COLORS.revista,
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  couponBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 15 },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  backButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: COLORS.bckbtn,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.black,
    flex: 1,
    textAlign: 'center',
  },
  placeholder: {
    width: 40,
  },
  paymentTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: COLORS.redblack,
  },
  paymentMethods: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 8,
    padding: 12,
    width: '48%',
    justifyContent: 'center',
    backgroundColor: COLORS.inputBackground,
  },
  selectedPayment: {
    borderColor: '#4caf50',
    backgroundColor: '#e0f2f1',
  },
  paymentText: { fontSize: 14, color: COLORS.reviewcmt },
  featuresRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  feature: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  featureText: { fontSize: 13, color: '#555', flex: 1, marginLeft: 8 },
  checkoutBtn: {
    backgroundColor: COLORS.revista,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  checkoutBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  continueBtn: { alignItems: 'center', padding: 12 },
  continueBtnText: { color: '#4caf50', fontSize: 15 },
});
export default styles;
